### ISSUE TITLE
Error: connect ECONNREFUSED 127.0.0.1:5000

### ISSUE THREAD

**Issue by yury-gurevich** [graykode/ai-docstring#5]
getting an error in WSL2 - extension is installed in WSL2 whilst documenting  Flask application. 

Error: connect ECONNREFUSED 127.0.0.1:5000

**Comment by MehdiAria** [comment]
Same problem here on Django project

**Comment by edoomm** [comment]
Same problem on vscode

![image](https://user-images.githubusercontent.com/57675992/159606504-13265603-8f9f-4c41-b2c8-dcce0816ba0b.png)

**Comment by garylavayou** [comment]
@yury-gurevich @MehdiAria @edoomm You need first to install the [AI model server](https://github.com/graykode/ai-docstring#1-run-the-container-for-the-model-inference-server) to enable the AI-based auto-generation of docstring.

**Comment by Tyler-Rendina** [comment]
Once the above is complete, run `docker ps` and update your extension setting to use the correct tcp address in the PORTS column

**Comment by AjayPrasadVerma** [comment]
"connect ECONNREFUSED 127.0.0.1:5000", Proble in node.js project
